### ISSUE TITLE
Lower The RAM Capacity Requirement

### ISSUE THREAD

**Issue by coolpro313** [harold-b/bladebit#2]
This is a suggestion/request which is to lower the RAM capacity requirement from 416GIB to either 128GB or even lower to 64GB just because not many motherboards can support that much ram most of them the max limit is between 32GB and128GB it wouldn't make sense to make a plotter that requires that much of ram so that's my suggestion/request to lower the ram capacity requirement from 416GIB to 128GB or even lower to 64GB

**Comment by paspy** [comment]
If you want a lower RAM requirement plotter you really should go find something else like official plotter or MadMax.
This is an all in memory plotter that intended replace all temp drive (SSDs) to RAM is designed to and required that much memory.

**Comment by coolpro313** [comment]
yes i understand that i'm using mad max i just find that it's way too much i didn't use this at all where my board's max is 128GB but i just find it way too high just for a normal user they'd need to basically buy a very high end like microsoft's servers just to use this software that's all i'm saying just a suggestion to lower the ram requirement so that everyone can use it instead of users with a very high end PC that supports 500+GB ram that's all that i'm saying

**Comment by fihzy** [comment]
"Hey make that Ferrari more crap, slower, and cheaper, so we can all get one!"

**Comment by harold-b** [comment]
Unfortunately, I can't magically reduce the size of the data required for plotting. It is not an arbitrary decision to require 416GiB of RAM, it is because this is what is required to process the data in RAM. I might be able to pull off some tricks to reduce RAM, but it wouldn't be by much. A single table's back pointers require 32GiB (8bytes * k^32), and there's 6 of those. 

I appreciate your feedback, though. I myself can't use this plotter. I don't have the hardware and I had to pay to rent a cloud system to develop it. If I have time, I might make a fast disk-based one. But I think people are pretty happy already with mad max, aren't day?

**Comment by coolpro313** [comment]
yes where most of them has the max of 128GB of ram that the boards supports but good idea to make a ram only plotter for quick plot times and have weak CPU's but to me 416GIB is too much for the software
